### ISSUE TITLE
Show album art

### ISSUE THREAD

**Issue by MartinStyk** [xstefank/pv243-music-library#2]
Album obsahuje byte[] albumArt. Pokial toto pole nie je prazdne, zobrazme album art v detaily albumu, pripadne aj v zozname albumov - (mozme ho ukladat aj v mensej velkosti ak je to potrebne)

Assignujem na obidvoch javascript specialistov

**Comment by MartinStyk** [comment]
Obrazok albumu dostanes po GET na /album/{id}/image. See #7

**Comment by lenkahe** [comment]
Album art zobrazujeme v overview aj v detaile.
