### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by MartinStyk** [xstefank/pv243-music-library#8]
- [x] 3 role 
- [x] registracia
- [x] prihlasenie
- [ ] hashovane heslo
- [x] zabezpecit REST endpointy
- [x] zabezpecit Websocket endpoint
- [x] Angular?

**Comment by MartinStyk** [comment]
@piskula , security sa riesi aj v Angulare, alebo sa zabezpecuje len REST endpoint?
@all, nejaky napad na 3 role (user, admin, ?) a konkretne rozdiely v ich pravomociach?

**Comment by xstefank** [comment]
admin - prava na aj na uzivatelov (vytvarat + bany mozno)
reg user - vsetko okrem uzivatelov + prispevky na websocket a podobne
guest - len prezerat ?

**Comment by MartinStyk** [comment]
Registracia, prihlasenie, to asi budeme musiet urobit. Dufam, ze posielanie e mailov pri zabudnutom hesle a podobne srandy nebudu potrebne
