### ISSUE TITLE
Firefox not responding

### ISSUE THREAD

**Issue by xstefank** [xstefank/pv243-music-library#9]
Skuste este niekto prosim, mozno je chyba u mna. Ale ak nie, tak je dost velka pravdepodobnost, ze to budu testovat na firefoxe. 

plus @piskula co to je "Capase"? :D

**Comment by MartinStyk** [comment]
u mna to funguje

**Comment by piskula** [comment]
Čapáše je:
keď skúšaš či niečo funguje, a potom to tam ostane, lebo to funguje
